### ISSUE TITLE
`::findByParam(array())` throws mysql exception

### ISSUE THREAD

**Issue by Jud** [lox/pheasant#107]
Currently:

```php
DomainObject::findById(array());
```
Throws a mysql exception since the sql translates to `where id in ()`. After searching around, I found [this stackoverflow post](http://stackoverflow.com/questions/3709703/sql-in-clause-with-zero-to-many-parameters) which suggests using `IN (null)` since even `null == null` is always false.

Would be easy to just test for this case in `$binder->reduce`. I can make a PR, but wanted to make sure you guys aren't already dealing with this through a different method.

**Comment by bjornpost** [comment]
Fixed in c0353fe.
