### ISSUE TITLE
Query builder should use back-ticks to escape identifiers

### ISSUE THREAD

**Issue by iamjochem** [lox/pheasant#121]
sometimes you have a field or table whose name clashes with a reserved word (hey it happens) ... proper escaping of identifiers in the generated SQL would make the pain go away.

**Comment by bjornpost** [comment]
According [to the tests here](https://github.com/lox/pheasant/blob/master/tests/Pheasant/Tests/TableCriteriaTest.php#L25-56) we're already escaping column names.

Table names are not escaped yet, but [we have some code](https://github.com/lox/pheasant/blob/master/tests/Pheasant/Tests/TableNameTest.php#L27) that returns quoted table names.

**Comment by Jud** [comment]
I have this fixed in a branch (we have an `Order` model, so it's pretty much a requirement to escape names). I'll see if I can cherry-pick the commits and submit a PR.
