### ISSUE TITLE
New maintainers required

### ISSUE THREAD

**Issue by lox** [lox/pheasant#129]
I'm struggling to keep up with Pheasant management, I'd love for some new maintainers to help out. 

@Jud @bjornpost would you guys be interested?

**Comment by Jud** [comment]
I'm down to help out. We're using pheasant, and have an interest in keeping it maintained.

**Comment by bjornpost** [comment]
Same here. I do not have much time, but I can help out keeping the issue list organized and help test PRs before pulling in.

**Comment by lox** [comment]
Thanks Guys, I'll add you both as collaborators and let's figure out how to get a new release out.

**Comment by bjornpost** [comment]
Cool. I already did some cleanup. @Jud, would you mind pulling in my PRs if they look good? Feels a bit weird to merge my own PRs without a second pair of eyes looking at it.

**Comment by lox** [comment]
I'd suggest we stick with a policy of needing 2 of the 3 of us to sign off on PRs?

**Comment by bjornpost** [comment]
Seems like a good policy.
