### ISSUE TITLE
Double hydrating when using `includes()`?

### ISSUE THREAD

**Issue by bjornpost** [lox/pheasant#130]
Just fiddled around with `includes()` again and noticed that it tries to hydrate objects twice. Most of the time it's just inefficient. But when using the DateTime Type, it throws an exception saying "DateTime::__construct() expects parameter 1 to be string, object given".

After some digging; I found that `Schema::hydrate()` is called twice for included DomainObjects. First, it's called from `\Pheasant\Collection::hydrate()` ([src](https://github.com/lox/pheasant/blob/master/lib/Pheasant/Collection.php#L40)), second time it's called from `Relationship::get()`, (f.e. BelongsTo ([src](https://github.com/lox/pheasant/blob/master/lib/Pheasant/Relationships/BelongsTo.php#L36))).

Just calling `return $cached;` in BelongsTo.php fixes the issue, but I'm not sure about possible unwanted side effects.

/cc @Jud

**Comment by Jud** [comment]
@bjornpost that's how we fixed it and haven't had any side effects (ditto for `HasOne`).

https://github.com/judsonco/pheasant/blob/9db99cb4fdf568f9664425e1c4ab16fa16dce071/lib/Pheasant/Relationships/BelongsTo.php#L23

I haven't had time to think about how that effects the ability to use a different, hypothetical, cache backend like memcached, but it doesn't seem like it would effect it.
