### ISSUE TITLE
Release Pheasant 1.3.2

### ISSUE THREAD

**Issue by bjornpost** [lox/pheasant#137]
Bug fix release.

Whats included: https://github.com/lox/pheasant/milestones/1.3.2

**Comment by bjornpost** [comment]
@Jud would you mind checking the PR's for this release and pull them in? Also: do you have fixes in your branch that are not included here yet? It would be great if we could get this released next week.

**Comment by Jud** [comment]
@bjornpost let me go through our branch and check. I'll also look over those pulls.

**Comment by bjornpost** [comment]
@lox is there a list of things that should be done/checked before releasing?

**Comment by bjornpost** [comment]
ping @lox :-)

**Comment by lox** [comment]
Nah, previously I'd get it into production on master before I declared it a stable release :)

**Comment by bjornpost** [comment]
Ok, proposal:

 - [x] All tests must pass on PHP 5.3, 5.4, 5.5 and 5.6. PHP 7 and HHVM may fail for now.
 - [x] When introducing new features: documentation with usage example(s) should be available
 - [ ] Write release notes to `CHANGELOG.md`
 - [ ] Tag release on Github
 - [ ] Releases must follow Server
 - [ ] Update our package on Packagist
 - [ ] Update our read the docs site?

**Comment by bjornpost** [comment]
v1.3.2 is released: https://github.com/lox/pheasant/releases/tag/v1.3.2
