### ISSUE TITLE
getpheasant.com unreachable

### ISSUE THREAD

**Issue by bjornpost** [lox/pheasant#145]
Domain resolves to an IP address, does not respond to ping. @lox, is this something you can look in to? I guess we do not really need the site, a simple 301 to readthedocs will suffice, I guess.

**Comment by lox** [comment]
This must be a github pages issue. I'll setup a redirect.

**Comment by Jud** [comment]
@lox, it appears the domain has expired.

**Comment by lox** [comment]
Eeep. Investigating.
