### ISSUE TITLE
PHP7 and HHVM compatibility

### ISSUE THREAD

**Issue by bjornpost** [lox/pheasant#148]
Since #139 we are building Pheasant for PHP7 and HHVM. Both fail at the moment. I guess that's something we should fix.

* Required change for PHP7 breaks the public API + needs manual upgrading, because `String` is a reserved classname in PHP7. If we keep following semver, this requires releasing Pheasant 2.0.0.
* HHVM compatibility requires some investigation. Currently it crashes on `data_seek(0)` (which is called when using `ResultIterator::rewind()`). The [HHVM docs](http://docs.hhvm.com/manual/en/mysqli-stmt.data-seek.php#refsect1-mysqli-stmt.data-seek-parameters) say that position 0 should work, but apparently it's not. [Could be a bug on their side](https://github.com/facebook/hhvm/issues/5025).

**Comment by bjornpost** [comment]
@lox, @jud: PHP 7.0.0 RC 1 was released 21 Aug. I think we should decide on which way to go regarding the reserved classnames. The easy way to fix this would be to suffix each type with `Type`. For example: `Pheasant\Types\Base` becomes `Pheasant\Types\BaseType`.

**Comment by Jud** [comment]
I played around with this in judsonco/pheasant@314d309408947e674cc7cfce078f42ba6650bb97  &mdash; and renaming the reserved words was enough to get tests passing in PHP7.

https://travis-ci.org/judsonco/pheasant/builds/73716715

In my commit I only renamed the reserved words, though it seems best to rename all types, and appending `Type` is pretty easy.

**Comment by bjornpost** [comment]
I will prepare a PR tonight.
